//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Locations
{

  private Suburb[] locationField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute("Location")]
  public Suburb[] Location
  {
    get
    {
      return this.locationField;
    }
    set
    {
      this.locationField = value;
    }
  }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class Suburb
{

  private int postCodeField;

  private string localityField;

  private string stateField;

  private string latitudeField;

  private string longitudeField;

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public int PostCode
  {
    get
    {
      return this.postCodeField;
    }
    set
    {
      this.postCodeField = (int)value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string Locality
  {
    get
    {
      return this.localityField;
    }
    set
    {
      this.localityField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string State
  {
    get
    {
      return this.stateField;
    }
    set
    {
      this.stateField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string Latitude
  {
    get
    {
      return this.latitudeField;
    }
    set
    {
      this.latitudeField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string Longitude
  {
    get
    {
      return this.longitudeField;
    }
    set
    {
      this.longitudeField = value;
    }
  }


  /// <summary>
  /// in house generated field will be ignored
  /// during the serialisation...
  /// </summary>
  [System.Xml.Serialization.XmlIgnore()]
  public string stateName
  {
    get
    {
      switch (stateField)
      {
        case "TAS":
          return "Tasmania";
        case "NT":
          return "Northern Territory";
        case "VIC":
          return "Victoria";
        case "NSW":
          return "New South Wales";
        case "SA":
          return "South Australia";
        case "WA":
          return "Western Australia";
        case "QLD":
          return "Queensland";
        default:
          return "";
      }
    }
  }
}
